
"""
 Initialises the visualisation taxonomy database entries
 according to TVCG definitions
"""

from web.models import TaxonomyArea, TaxonomyCategory, TaxonomyItem, Reference

def taxonomy_init():
	rs = TaxonomyArea.objects.all()
	for x in rs:
		x.delete()

	rs = TaxonomyCategory.objects.all()
	for x in rs:
		x.delete()

	rs = TaxonomyItem.objects.all()
	for x in rs:
		x.delete()

	a = TaxonomyArea(name="Visualisation")
	a.save()

	r = TaxonomyCategory(name="Theory of Visual Analysis", area=a)
	r.save()
	TaxonomyItem(name="Design Methodologies", category=r).save()
	TaxonomyItem(name="Taxonomies", category=r).save()
	TaxonomyItem(name="Visual Analysis Models", category=r).save()
	TaxonomyItem(name="Visualization Models", category=r).save()

	r = TaxonomyCategory(name="Visual Analysis and Knowledge Discovery", area=a)
	r.save()
	TaxonomyItem(name="Hypothesis Forming", category=r).save()
	TaxonomyItem(name="Hypothesis Testing, Visual Evidence", category=r).save()
	TaxonomyItem(name="Knowledge Externalization", category=r).save()
	TaxonomyItem(name="Visual Knowledge Discovery", category=r).save()
	TaxonomyItem(name="Visual Knowledge Representation", category=r).save()

	r = TaxonomyCategory(name="Data Handling, Processing and Analysis", area=a)
	r.save()
	TaxonomyItem(name="Data Acquisition and Management", category=r).save()
	TaxonomyItem(name="Data Aggregation", category=r).save()
	TaxonomyItem(name="Data Cleaning", category=r).save()
	TaxonomyItem(name="Data Clustering", category=r).save()
	TaxonomyItem(name="Data Fusion and Integration", category=r).save()
	TaxonomyItem(name="Data Registration", category=r).save()
	TaxonomyItem(name="Data Segmentation", category=r).save()
	TaxonomyItem(name="Data Smoothing", category=r).save()
	TaxonomyItem(name="Data Transformation and Representation", category=r).save()
	TaxonomyItem(name="Feature Detection and Tracking", category=r).save()
	TaxonomyItem(name="Machine Learning", category=r).save()

	r = TaxonomyCategory(name="Non-Spatial Data and Techniques", area=a)
	r.save()
	TaxonomyItem(name="Dimensionality Reduction", category=r).save()
	TaxonomyItem(name="Graph/Network Data", category=r).save()
	TaxonomyItem(name="Hierarchy Data", category=r).save()
	TaxonomyItem(name="High-Dimensional Data", category=r).save()
	TaxonomyItem(name="Parallel Coordinates", category=r).save()
	TaxonomyItem(name="Pixel-oriented Techniques", category=r).save()
	TaxonomyItem(name="Statistical Graphics", category=r).save()
	TaxonomyItem(name="Tabular Data", category=r).save()
	TaxonomyItem(name="Text and Document Data", category=r).save()
	TaxonomyItem(name="Time Series Data", category=r).save()

	r = TaxonomyCategory(name="Spatial Data and Techniques", area=a)
	r.save()
	TaxonomyItem(name="Extraction of Surface (Isosurfaces, Material Boundaries)", category=r).save()
	TaxonomyItem(name="Geometry-based Techniques", category=r).save()
	TaxonomyItem(name="Irregular and Unstructured Grids", category=r).save()
	TaxonomyItem(name="PDE's and Visualization", category=r).save()
	TaxonomyItem(name="Point-based Data", category=r).save()
	TaxonomyItem(name="Scalar Field Data", category=r).save()
	TaxonomyItem(name="Tensor Field Data", category=r).save()
	TaxonomyItem(name="Topology-bsaed Techniques", category=r).save()
	TaxonomyItem(name="Vector Field Data", category=r).save()
	TaxonomyItem(name="Volume Modeling", category=r).save()
	TaxonomyItem(name="Volume Rendering", category=r).save()

	r = TaxonomyCategory(name="Interaction Techniques", area=a)
	r.save()
	TaxonomyItem(name="Coordinated and Multiple Views", category=r).save()
	TaxonomyItem(name="Data Editing", category=r).save()
	TaxonomyItem(name="Focus + Context Techniques", category=r).save()
	TaxonomyItem(name="Human Factors", category=r).save()
	TaxonomyItem(name="Human-Computer Interaction", category=r).save()
	TaxonomyItem(name="Interaction Design", category=r).save()
	TaxonomyItem(name="Manipulation and Deformation", category=r).save()
	TaxonomyItem(name="User Interfaces", category=r).save()
	TaxonomyItem(name="Zooming and Navigation Techniques", category=r).save()

	r = TaxonomyCategory(name="Display and Interaction Technology", area=a)
	r.save()
	TaxonomyItem(name="Haptics for Visualization", category=r).save()
	TaxonomyItem(name="Immersive and Virtual Environments", category=r).save()
	TaxonomyItem(name="Large and High-res Displays", category=r).save()
	TaxonomyItem(name="Multimodel Input Devices", category=r).save()
	TaxonomyItem(name="Stereo Displays", category=r).save()

	r = TaxonomyCategory(name="Evaluation", area=a)
	r.save()
	TaxonomyItem(name="Field Studies", category=r).save()
	TaxonomyItem(name="Laboratory Studies", category=r).save()
	TaxonomyItem(name="Metrics and Benchmarks", category=r).save()
	TaxonomyItem(name="Qualitative Evaluation", category=r).save()
	TaxonomyItem(name="Quantitative Evaluation", category=r).save()
	TaxonomyItem(name="Task and Requirements Analaysis", category=r).save()
	TaxonomyItem(name="Usability Studies", category=r).save()

	r = TaxonomyCategory(name="Perception and Cognition", area=a)
	r.save()
	TaxonomyItem(name="Attention and Blindness", category=r).save()
	TaxonomyItem(name="Cognition Theory", category=r).save()
	TaxonomyItem(name="Cognitive and Perceptual Skill", category=r).save()
	TaxonomyItem(name="Color Perception", category=r).save()
	TaxonomyItem(name="Distributed Cognition", category=r).save()
	TaxonomyItem(name="Embodied / Enactive Cognition", category=r).save()
	TaxonomyItem(name="Motion Perception", category=r).save()
	TaxonomyItem(name="Perception Theory", category=r).save()
	TaxonomyItem(name="Perception Cognition", category=r).save()
	TaxonomyItem(name="Scene Perception", category=r).save()
	TaxonomyItem(name="Texture Perception", category=r).save()

	r = TaxonomyCategory(name="Hardware Acceleration", area=a)
	r.save()
	TaxonomyItem(name="CPU and GPU Clusters", category=r).save()
	TaxonomyItem(name="Distributed Systems and Grid Environments", category=r).save()
	TaxonomyItem(name="GPUs and Multi-core Architectures", category=r).save()
	TaxonomyItem(name="Parallel Systems", category=r).save()
	TaxonomyItem(name="Special Purpose Hardware", category=r).save()
	TaxonomyItem(name="Volume Graphics Hardware", category=r).save()

	r = TaxonomyCategory(name="Large Data Vis", area=a)
	r.save()
	TaxonomyItem(name="Compression Techniques", category=r).save()
	TaxonomyItem(name="Multi-field, Multi-modal and Multi-variate Data", category=r).save()
	TaxonomyItem(name="Multidimensional Data", category=r).save()
	TaxonomyItem(name="Multiresolution Techniques", category=r).save()
	TaxonomyItem(name="Petascale Techniques", category=r).save()
	TaxonomyItem(name="Streaming Data", category=r).save()
	TaxonomyItem(name="Time-varying Data", category=r).save()

	r = TaxonomyCategory(name="General Topics and Techniques", area=a)
	r.save()
	TaxonomyItem(name="Aesthetics in Visualization", category=r).save()
	TaxonomyItem(name="Animation", category=r).save()
	TaxonomyItem(name="Collaborative and Distributed Visualization", category=r).save()
	TaxonomyItem(name="Design Studies", category=r).save()
	TaxonomyItem(name="Glyph-based Techniques", category=r).save()
	TaxonomyItem(name="Illustrative Rendering", category=r).save()
	TaxonomyItem(name="Integrating Spatial and Non-spatial Data Visualization", category=r).save()
	TaxonomyItem(name="Mathematical Foundations for Visualization", category=r).save()
	TaxonomyItem(name="Mobile and Ubiquitous Visualization", category=r).save()
	TaxonomyItem(name="Presentation, Production and Dissemination", category=r).save()
	TaxonomyItem(name="Scalability Issues", category=r).save()
	TaxonomyItem(name="Sonification", category=r).save()
	TaxonomyItem(name="Uncertainty Visualization", category=r).save()
	TaxonomyItem(name="View-dependent Visualization", category=r).save()
	TaxonomyItem(name="Visual Design", category=r).save()
	TaxonomyItem(name="Visualization System and Toolkit Design", category=r).save()

	r = TaxonomyCategory(name="Applications", area=a)
	r.save()
	TaxonomyItem(name="Bioinformatics Visualization", category=r).save()
	TaxonomyItem(name="Biomedical and Medical Visualization", category=r).save()
	TaxonomyItem(name="Business and Finance Visualization", category=r).save()
	TaxonomyItem(name="Data Warehousing, Data Visualization and Data Mining", category=r).save()
	TaxonomyItem(name="Flow Visualization", category=r).save()
	TaxonomyItem(name="Geographic/Geospatial Visualization", category=r).save()
	TaxonomyItem(name="Molecular Visualization", category=r).save()
	TaxonomyItem(name="Multimedia (Image/Video/Music) Visualization", category=r).save()
	TaxonomyItem(name="Software Visualization", category=r).save()
	TaxonomyItem(name="Terrain Visualization", category=r).save()
	TaxonomyItem(name="Visualization for the Masses", category=r).save()
	TaxonomyItem(name="Visualization in Earth, Space and Environmental Sciences", category=r).save()
	TaxonomyItem(name="Visualization in Education", category=r).save()
	TaxonomyItem(name="Visualization in Mathematics", category=r).save()
	TaxonomyItem(name="Visualization in Physical Sciences and Engineering", category=r).save()
	TaxonomyItem(name="Visualization in Social and Information Sciences ", category=r).save()
	TaxonomyItem(name="Visualization in the Humanities", category=r).save()

	r = TaxonomyCategory(name="Visual Analytics Applications", area=a)
	r.save()
	TaxonomyItem(name="Emergency/Disaster Management", category=r).save()
	TaxonomyItem(name="Intelligence Analysis", category=r).save()
	TaxonomyItem(name="Network Security and Intrusion", category=r).save()
	TaxonomyItem(name="Privacy and Security", category=r).save()
	TaxonomyItem(name="Sensor Networks", category=r).save()
	TaxonomyItem(name="Situational Awareness", category=r).save()
	TaxonomyItem(name="Time Critical Applications", category=r).save()

taxonomy_init()
